// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCtlio4QaY_tiKCsb5UsxnAb6yYE7H2pVA',
    appId: '1:857131450044:web:9ce7e9a52ee6dd1bcbdab9',
    messagingSenderId: '857131450044',
    projectId: 'fir-flutter-codetsa',
    authDomain: 'fir-flutter-codetsa.firebaseapp.com',
    storageBucket: 'fir-flutter-codetsa.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8XahwGqd93IdY66d7_-m2k2vYQQ3URgI',
    appId: '1:857131450044:android:1a0ccde1a2c791b0cbdab9',
    messagingSenderId: '857131450044',
    projectId: 'fir-flutter-codetsa',
    storageBucket: 'fir-flutter-codetsa.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADgAA1SJhegsWJQHDh7WRsG1G4x0d_qBE',
    appId: '1:857131450044:ios:33b1841657c1a430cbdab9',
    messagingSenderId: '857131450044',
    projectId: 'fir-flutter-codetsa',
    storageBucket: 'fir-flutter-codetsa.appspot.com',
    iosClientId: '857131450044-1gsr3iapkas6of0cvfkpt8otimh7tb2c.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterFirestoreFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyADgAA1SJhegsWJQHDh7WRsG1G4x0d_qBE',
    appId: '1:857131450044:ios:33b1841657c1a430cbdab9',
    messagingSenderId: '857131450044',
    projectId: 'fir-flutter-codetsa',
    storageBucket: 'fir-flutter-codetsa.appspot.com',
    iosClientId: '857131450044-1gsr3iapkas6of0cvfkpt8otimh7tb2c.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterFirestoreFirebase',
  );
}
